const GET_COUPON = 'GET_COUPON'
const ISSUE_COUPON = 'ISSUE_COUPON'
const COUPONS = 'COUPONS'
const LOADING = 'LOADING'
const SNACKBAR = 'SNACKBAR'

export default {GET_COUPON, ISSUE_COUPON, COUPONS, LOADING, SNACKBAR}
